"""
Order creation endpoint with MaxMind geo-fraud protection.
"""

from __future__ import annotations

from fastapi import APIRouter, Request
from pydantic import BaseModel, Field

from app.api.deps import get_client_ip, verify_order_geo

router = APIRouter(prefix="/orders", tags=["orders"])


class CustomerIn(BaseModel):
    name: str = Field(..., min_length=2, max_length=100)
    phone: str = Field(..., pattern=r"^(\+966|966|05|5)\d{8}$")


class OrderItemIn(BaseModel):
    product_id: str
    quantity: int = Field(..., ge=1, le=3)
    offer_price_sar: int
    is_upsell: bool = False


class OrderTotalsIn(BaseModel):
    subtotal_sar: int
    total_sar: int
    currency: str = "SAR"


class OrderCreateIn(BaseModel):
    customer: CustomerIn
    items: list[OrderItemIn]
    totals: OrderTotalsIn
    payment_method: str = "cod"
    event_ids: dict = Field(default_factory=dict)
    attribution: dict = Field(default_factory=dict)


class OrderCreateOut(BaseModel):
    success: bool = True
    order_number: str
    message_ar: str = "تم استلام طلبك بنجاح"


@router.post("", response_model=OrderCreateOut)
async def create_order(body: OrderCreateIn, request: Request):
    client_ip = get_client_ip(request)

    # Geo-fraud check with phone whitelist support
    geo_result = await verify_order_geo(ip=client_ip, phone=body.customer.phone)

    # If we reach here, the order is allowed.
    # Store geo metadata with the order for analytics.
    geo_metadata = {
        "client_ip": client_ip,
        "country_iso": geo_result.country_iso,
        "risk_score": geo_result.risk_score,
        "geo_reason": geo_result.reason,
    }

    # TODO: validate phone (KSA format), recalculate totals, persist order,
    #       send to Google Sheets, fire CAPI events.
    #       (Covered by other services in the architecture)

    order_number = "MYM-PLACEHOLDER-0001"  # Generated by order service

    return OrderCreateOut(
        order_number=order_number,
        message_ar="تم استلام طلبك بنجاح",
    )
